dist: trusty
language: node_js
node_js:
- '6'
script:
- npm run report-coverage
- npm run lint
env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - git-core
    packages:
      - g++-4.9
      - git
